import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-screen">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex justify-between items-center w-full h-[64px]">
          <div className="flex mx-4">
            <p className="text-[14px]/[16px] font-[600] tracking-[-2%] py-2 px-4 mr-2">
              SKINSTRIC
            </p>
            <div className="flex justify-center items-center">
              <Image src="/rectangleL.svg" height={17} width={4} alt="rectangle"/>
              <p className="font-semibold text-[#1A1B1C] text-[14px]/[16px] tracking-[-2%] opacity-60 px-2">
                INTRO
              </p>
              <Image src="/rectangleR.svg" height={17} width={4} alt="rectangle"/>
            </div>
          </div>
          <div className="mx-4">
            <button className="bg-[#1A1B1C] text-white py-2 px-4 text-[14px]/[16px]">
              Enter Code
            </button>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
